# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c6fb051edcbed9cd0d2ef513db834c397891d0d8ee24992f5cbdecf97220cf4610fb25fc1c512de4060ce05783454b161a91200a0d14831db80262552c37648

test:
  secret_key_base: 8f8cbd97c481b2ff93986f2083d04b405e0f449f47369af72bc6a50f07368c5b637fb7ed9f0489e5102903e57889bcd9f74c1234ea93c2706edf2925ca3a3957

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
